### ISSUE TITLE
binify_fixations() is really slow

### ISSUE THREAD

**Issue by tjmahr** [dmirman-zz/gazer#5]
The code looks like it's growing a data frame by a step on each iteration of a for-loop. (Note the rbind()). That's a common performance killer. The alternative would be to split the dataframe up into a list, work on each chunk in the list, then combine them altogether in the end.

```
  for(f in 1:max(gaze$FixationID)){ # for each fixation
    this_fix <- subset(gaze, FixationID == f)
    fix_bins <- ceiling(this_fix$CURRENT_FIX_START/binSize):ceiling(this_fix$FixEnd/binSize)
    if(f==1){ #first fixation: initialize gaze_bins
      gaze_bins <- data.frame(FixationID = 1, timeBin = fix_bins)
    } else { #other fixations: append to gaze_bins
      gaze_bins <- rbind(gaze_bins, data.frame(FixationID = f, timeBin = fix_bins))
    }
  }
```

**Comment by dmirman-zz** [comment]
I agree. I feel like `dplyr` should be able to do exactly this, but I haven't been able to get it to work. The problem seems to be that typical `dplyr` functions like `summarize` and `mutate` want to either collapse to a single value or to keep same number of values, but we're expanding a fixation into a series of time bins.
